import { generateContentPrompt } from '@/content/authoring/generate-content-prompt';
import {
  getNcEocChunk,
  NC_EOC_CHUNKS,
  NC_EOC_MODULE,
  type NcEocChunkId,
} from '@/content/authoring/nc-eoc-chunks';
import { ncEocInstructionsSection } from '@/content/authoring/sections/nc-eoc-instructions';
import { outputSection } from '@/content/authoring/sections/output';
import type { AuthorPromptOptions } from '@/content/authoring/types';

export type NcEocPromptOptions = {
  chunkId: NcEocChunkId;
  /** Optional pasted EOC items, textbook excerpt, or class notes for this strand. */
  sourceMaterial?: string;
  authorRef?: string;
};

export function generateNcEocPrompt(options: NcEocPromptOptions): string {
  const chunk = getNcEocChunk(options.chunkId);
  const authorRef = options.authorRef?.trim() || 'ken';

  const base: AuthorPromptOptions = {
    topic: `NC Biology EOC — ${chunk.roomTitle}`,
    moduleTitle: 'Biology EOC Review',
    wingIdPrefix: 'bio.eoc',
    sourceKind: 'example-questions',
    sourceMaterial:
      options.sourceMaterial?.trim() ||
      chunk.sourceMaterialHint +
        '\n\nUse the 2023 NC Biology standards (LS.Bio.*) and 2025 released EOC form patterns.',
    scope: 'room',
    authorRef,
  };

  return [
    generateContentPrompt(base),
    ncEocInstructionsSection(chunk),
    mergeInstructionsSection(),
    outputSection(),
  ].join('\n\n');
}

function mergeInstructionsSection(): string {
  return `# After you respond

The author saves your JSON as \`plan/inbox/bio-eoc-<room-slug>.json\`. Multiple room files merge into one module before bundling alongside existing \`biochem.*\` content in the repo.

Do **not** include rooms already marked done unless explicitly asked to expand them.`;
}

/** One-shot master brief for an external LLM building the whole EOC program. */
export function generateNcEocMasterBrief(): string {
  const pending = NC_EOC_CHUNKS.filter((c) => c.status === 'pending');
  const done = NC_EOC_CHUNKS.filter((c) => c.status === 'done');

  const fileList = NC_EOC_CHUNKS.map(
    (c) =>
      `- \`bio-eoc-${c.outFileSlug}.json\` — ${c.roomTitle} (${c.status === 'done' ? 'DONE' : `${c.unitCount} units`})`,
  ).join('\n');

  return `# NC Biology EOC — multi-file build program

Build a **complete** study module for the North Carolina Biology End-of-Course exam (2023 NCSCOS, 2025 operational form). Deliver **one JSON file per room** — not one giant file.

## Module identity (same in every file)

- \`id\`: \`${NC_EOC_MODULE.id}\`
- \`title\`: \`${NC_EOC_MODULE.title}\`
- Wing \`id\`: \`${NC_EOC_MODULE.wingId}\`
- All unit achievements use \`wingId: "${NC_EOC_MODULE.wingId}"\`

## Files to produce

${fileList}

## Workflow

1. Author **one room per conversation turn** (keeps quality high).
2. Each response = raw JSON only (no markdown fences).
3. Save as \`plan/inbox/bio-eoc-<slug>.json\`.
4. After each file, say which file is next.

## Already done — do not regenerate

${done.map((c) => `- \`bio-eoc-${c.outFileSlug}.json\` (${c.unitCount} units)`).join('\n')}

## Build order (recommended)

${pending.map((c, i) => `${i + 1}. **${c.roomTitle}** → \`bio-eoc-${c.outFileSlug}.json\` (${c.objectives[0]?.split('—')[0]?.trim() ?? c.id})`).join('\n')}

## Per-chunk prompts

For each pending room, the author will paste a chunk-specific prompt generated by \`generateNcEocPrompt({ chunkId: '...' })\`. Use that prompt's schema sections and NC instructions.

## Merge (author's repo — not your job)

Ken merges all room files into one \`bio.eoc\` wing, then integrates with existing bundled \`biochem.*\` units (35 units from worksheet scans). New EOC units **supplement and replace** thin coverage; both ID namespaces coexist.

## Quality targets

- ~35–45 total KnowledgeUnits across all files
- Every NC LS.Bio objective covered at least once in \`authorNotes\`
- 24–32% Heredity + 26–34% Molecules get the most units (match test blueprint weights)
- At least one interactive (non-MC/fill-only) quiz per unit`;
}
