// AUTO-GENERATED from the "EOC Review Inclusive" quiz doc. Answer keys derived by subject review.
// Source: Google Doc 1JgIrFzbWcg1vXySKmEspil8vyKLYEgZAFczSwPkozzw

export type QuizChoice = { letter: string; text: string };
export type QuizQuestion = {
  n: number;
  prompt: string;
  choices: QuizChoice[];
  answer: string; // letter of the correct choice
};

export const T1_QUIZ_TITLE = "EOC Review Inclusive";

export const T1_QUIZ: QuizQuestion[] = [
  {
    n: 1,
    prompt: 'This is a codon chart. A strand of DNA with the sequence GAA CCG GGG undergoes a mutation, and the first G is changed to an A. How will this mutation affect the amino acid sequence?',
    choices: [
      { letter: 'A', text: 'One amino acid will change.' },
      { letter: 'B', text: 'Two amino acids will change.' },
      { letter: 'C', text: 'All of the amino acids will change.' },
      { letter: 'D', text: 'All of the amino acids will remain the same.' },
    ],
    answer: 'A',
  },
  {
    n: 2,
    prompt: 'What is most likely to result when a mutation affects a DNA sequence?',
    choices: [
      { letter: 'A', text: 'The codons will be unable to create bonds with the enzymes.' },
      { letter: 'B', text: 'The nucleic acids will be unable to create bonds with the ribosomes.' },
      { letter: 'C', text: 'The amino acid sequence will be changed and a different protein will be formed.' },
      { letter: 'D', text: 'The protein sequence will be changed and a different set of nucleic acids will be formed.' },
    ],
    answer: 'C',
  },
  {
    n: 3,
    prompt: 'A mutation in which cell can create a change in heritable traits?',
    choices: [
      { letter: 'A', text: 'body cell' },
      { letter: 'B', text: 'gamete cell' },
      { letter: 'C', text: 'somatic cell' },
      { letter: 'D', text: 'prokaryote cell' },
    ],
    answer: 'B',
  },
  {
    n: 4,
    prompt: 'Which process produces mRNA from DNA?',
    choices: [
      { letter: 'A', text: 'synthesis' },
      { letter: 'B', text: 'replication' },
      { letter: 'C', text: 'translation' },
      { letter: 'D', text: 'transcription' },
    ],
    answer: 'D',
  },
  {
    n: 5,
    prompt: 'Which RNA is a copy made from a DNA strand that can be transported to a ribosome?',
    choices: [
      { letter: 'A', text: 'mRNA' },
      { letter: 'B', text: 'rRNA' },
      { letter: 'C', text: 'siRNA' },
      { letter: 'D', text: 'tRNA' },
    ],
    answer: 'A',
  },
  {
    n: 6,
    prompt: 'Which RNA sequence will result from the transcription of the DNA sequenceAAT TTC CGA ATG GGA?',
    choices: [
      { letter: 'A', text: 'AAU UUC CGA AUG GGA' },
      { letter: 'B', text: 'AGG GTA AGC CTT TAA' },
      { letter: 'C', text: 'TTU UUG GCT TUC CCT' },
      { letter: 'D', text: 'UUA AAG GCU UAC CCU' },
    ],
    answer: 'D',
  },
  {
    n: 7,
    prompt: 'A codon chart is shown below. What amino acid sequence would be produced from the DNA sequence TAC CCC GCA AGT?',
    choices: [
      { letter: 'A', text: 'Tyrosine - Proline - Alanine - Serine' },
      { letter: 'B', text: 'Methionine - Proline - Alanine - Serine' },
      { letter: 'C', text: 'Isoleucine - Glycine - Proline - Tyrosine' },
      { letter: 'D', text: 'Methionine - Glycine - Arginine - Serine' },
    ],
    answer: 'D',
  },
  {
    n: 8,
    prompt: 'Which statement best explains how mutations change the shape of flu virus antigens, preventing the attachment of antibodies?',
    choices: [
      { letter: 'A', text: 'Mutations allow for the exchange of antigens among virus species.' },
      { letter: 'B', text: 'Mutations cause overproduction of new antigens on the surface of the virus.' },
      { letter: 'C', text: 'Mutations change the amino acid sequence of the protein, resulting in a change in the nucleotide sequence.' },
      { letter: 'D', text: 'Mutations change the nucleotide sequence of the gene, resulting in a different arrangement of amino acids.' },
    ],
    answer: 'D',
  },
  {
    n: 9,
    prompt: 'Which best describes a strand of DNA?',
    choices: [
      { letter: 'A', text: 'It is a single-stranded nucleic acid with ribose and uracil.' },
      { letter: 'B', text: 'It is a double-stranded nucleic acid with deoxyribose and uracil.' },
      { letter: 'C', text: 'It is a single-stranded nucleic acid with deoxyribose and thymine.' },
      { letter: 'D', text: 'It is a double-stranded nucleic acid with deoxyribose and thymine.' },
    ],
    answer: 'D',
  },
  {
    n: 10,
    prompt: 'Why is DNA replication considered a semi-conservative process?',
    choices: [
      { letter: 'A', text: 'RNA will combine with DNA using the base pair rules during this process.' },
      { letter: 'B', text: 'DNA replication must occur before mitosis to produce identical daughter cells.' },
      { letter: 'C', text: 'DNA has two sides of complementary base pairs held together by weak bonds.' },
      { letter: 'D', text: 'The new DNA molecules contain one strand of the original molecule and one new strand.' },
    ],
    answer: 'D',
  },
  {
    n: 11,
    prompt: 'Which situation is most likely to result in a mutation that is passed on to an offspring?',
    choices: [
      { letter: 'A', text: 'ultraviolet radiation causing skin cancer' },
      { letter: 'B', text: 'a longtime smoker developing cancer in the lungs' },
      { letter: 'C', text: 'exposure to a chemical that affects gamete formation' },
      { letter: 'D', text: 'exposure to a chemical that affects the nervous system' },
    ],
    answer: 'C',
  },
  {
    n: 12,
    prompt: 'In which level of protein structure would a change most likely result in the formation of a different protein?',
    choices: [
      { letter: 'A', text: 'primary' },
      { letter: 'B', text: 'secondary' },
      { letter: 'C', text: 'tertiary' },
      { letter: 'D', text: 'quaternary' },
    ],
    answer: 'A',
  },
  {
    n: 13,
    prompt: 'Which is a result of the replication of DNA during meiosis?',
    choices: [
      { letter: 'A', text: 'production of amino acids' },
      { letter: 'B', text: 'formation of sister chromatids' },
      { letter: 'C', text: 'formation of more mitochondria' },
      { letter: 'D', text: 'production of multiple strands of mRNA' },
    ],
    answer: 'B',
  },
  {
    n: 14,
    prompt: 'Prior to mitosis, a cell will undergo replication to copy the DNA before dividing. Which feature of DNA allows the replication to be semi-conservative and equip the new cell with an exact copy of the genes from the parent cell?',
    choices: [
      { letter: 'A', text: 'DNA is single-stranded.' },
      { letter: 'B', text: 'DNA is transcribed into RNA before translation.' },
      { letter: 'C', text: 'Hydrogen bonds hold the strands closely together.' },
      { letter: 'D', text: 'Base pairing occurs between complementary strands.' },
    ],
    answer: 'D',
  },
  {
    n: 15,
    prompt: 'When is the amino acid sequence of a protein most likely to be altered?',
    choices: [
      { letter: 'A', text: 'when the protein experiences a change in function' },
      { letter: 'B', text: 'when there is a change in the DNA sequence that codes for the protein' },
      { letter: 'C', text: 'when the ribosome changes the order in which the amino acids are placed' },
      { letter: 'D', text: 'when the environment of the cell becomes warm enough to denature the protein' },
    ],
    answer: 'B',
  },
  {
    n: 16,
    prompt: 'A scientist observes thymine-thymine dimers in DNA instead of the expected thymine-adenine nucleotide pairing. What is most likely to have caused this change?',
    choices: [
      { letter: 'A', text: 'a new gene resulting from crossing over' },
      { letter: 'B', text: 'mutations induced by the environment' },
      { letter: 'C', text: 'nondisjunction of chromosomes' },
      { letter: 'D', text: 'a mutation in a gamete' },
    ],
    answer: 'B',
  },
  {
    n: 17,
    prompt: 'Which statement correctly describes the relationship between genes, proteins, and traits?',
    choices: [
      { letter: 'A', text: 'Genes are translated into proteins. The proteins are then transcribed into mRNA, which determines specific traits.' },
      { letter: 'B', text: 'Traits are translated into genes. The genes are then transcribed into mRNA, which determines specific proteins.' },
      { letter: 'C', text: 'Genes are transcribed into mRNA. The mRNA is then translated into proteins, which determine specific traits.' },
      { letter: 'D', text: 'Traits are transcribed into mRNA. The mRNA is then translated into genes, which determine specific proteins.' },
    ],
    answer: 'C',
  },
  {
    n: 18,
    prompt: 'A child is diagnosed with a rare genetic disorder. Neither parent has the disorder. Which statement best describes how the child might have inherited the disorder?',
    choices: [
      { letter: 'A', text: 'The disorder is sex-linked and is carried by the father.' },
      { letter: 'B', text: 'The disorder is dominant and is carried by one parent.' },
      { letter: 'C', text: 'The disorder is recessive and is carried by both parents.' },
      { letter: 'D', text: 'The disorder could only have been caused by a mutation during mitosis because neither parent has the disorder.' },
    ],
    answer: 'C',
  },
  {
    n: 19,
    prompt: 'Where is information stored that determines the function of a protein?',
    choices: [
      { letter: 'A', text: 'in the ribosome' },
      { letter: 'B', text: 'in the mitochondria' },
      { letter: 'C', text: 'in the nucleotide sequence of DNA' },
      { letter: 'D', text: 'in the amino acid sequence of rRNA' },
    ],
    answer: 'C',
  },
  {
    n: 20,
    prompt: 'Which correctly matches a strand of DNA with its complementary strand of RNA?',
    choices: [
      { letter: 'A', text: 'DNA: TAC TAG\nRNA: ATG AUC' },
      { letter: 'B', text: 'DNA: ATA CCG\nRNA: UAU GGC' },
      { letter: 'C', text: 'DNA: CUG AUU\nRNA: GAC UAA' },
      { letter: 'D', text: 'DNA: TAA CGC\nRNA: ATT GGG' },
    ],
    answer: 'B',
  },
  {
    n: 21,
    prompt: 'Fur color in a specific animal is controlled by a sex-linked, codominant trait, where some animals have black fur (B), some animals have orange fur (R), and some animals have brown-patterned fur (BR). A female with brown-patterned fur mates with a male that has black fur and has a female offspring. What is the probability that the female offspring will have brown-patterned fur?',
    choices: [
      { letter: 'A', text: '0%' },
      { letter: 'B', text: '25%' },
      { letter: 'C', text: '50%' },
      { letter: 'D', text: '100%' },
    ],
    answer: 'C',
  },
  {
    n: 22,
    prompt: 'Black hair color is dominant to white hair color in mice. Interpret the Punnett square below to determine the expected phenotypic ratio for the offpring of a homozygous black mouse and a white mouse.',
    choices: [
      { letter: 'A', text: '4 Black: 0 White' },
      { letter: 'B', text: '3 Black: 1 White' },
      { letter: 'C', text: '2 Black: 2 White' },
      { letter: 'D', text: '0 Black: 4 White' },
    ],
    answer: 'A',
  },
  {
    n: 23,
    prompt: 'Black hair color is dominant to white hair color in mice. Interpret the Punnett square below to determine the expected phenotypic ratio for the offpring of a heterozygous black mouse and a white mouse.',
    choices: [
      { letter: 'A', text: '4 Black: 0 White' },
      { letter: 'B', text: '3 Black: 1 White' },
      { letter: 'C', text: '2 Black: 2 White' },
      { letter: 'D', text: '0 Black: 4 White' },
    ],
    answer: 'C',
  },
  {
    n: 24,
    prompt: 'Black hair color in mice is dominant to white hair color. Which Punnett square depicts a cross between two heterozygous black mice?',
    choices: [
      {
        letter: 'A',
        text: 'BB × bb\n    ┌───┬───┬───┐\n    │   │ b │ b │\n    ├───┼───┼───┤\n    │ B │Bb │Bb │\n    ├───┼───┼───┤\n    │ B │Bb │Bb │\n    └───┴───┴───┘\n',
      },
      {
        letter: 'B',
        text: 'Bb × bb\n    ┌───┬───┬───┐\n    │   │ b │ b │\n    ├───┼───┼───┤\n    │ B │Bb │bb │\n    ├───┼───┼───┤\n    │ b │Bb │bb │\n    └───┴───┴───┘',
      },
      {
        letter: 'C',
        text: 'Bb × Bb\n    ┌───┬───┬───┐\n    │   │ B │ b │\n    ├───┼───┼───┤\n    │ B │BB │Bb │\n    ├───┼───┼───┤\n    │ b │Bb │bb │\n    └───┴───┴───┘',
      },
      {
        letter: 'D',
        text: 'bb × bb\n    ┌───┬───┬───┐\n    │   │ b │ b │\n    ├───┼───┼───┤\n    │ b │bb │bb │\n    ├───┼───┼───┤\n    │ b │bb │bb │\n    └───┴───┴───┘',
      },
    ],
    answer: 'C',
  },
  {
    n: 25,
    prompt: 'The development of heart disease is based on a genetic trait. Which action may delay the onset of the disease?',
    choices: [
      { letter: 'A', text: 'eating only organic vegetables' },
      { letter: 'B', text: 'restricting strenuous physical activity' },
      { letter: 'C', text: 'limiting the amount of protein consumed' },
      { letter: 'D', text: 'consuming a diet that is low in sodium and fats' },
    ],
    answer: 'D',
  },
  {
    n: 26,
    prompt: 'How can poor nutrition lead to a change in trait expression?',
    choices: [
      { letter: 'A', text: 'by changing genotype' },
      { letter: 'B', text: 'by changing karyotype' },
      { letter: 'C', text: 'by changing phenotype' },
      { letter: 'D', text: 'by changing inheritable traits' },
    ],
    answer: 'C',
  },
  {
    n: 27,
    prompt: 'Which example best demonstrates an organism’s interaction with the environment affecting gene expression?',
    choices: [
      { letter: 'A', text: 'a monkey learning to use a twig to capture termites for food' },
      { letter: 'B', text: 'a fox producing more offspring when prey are readily available' },
      { letter: 'C', text: 'a fish entering saltier waters and producing glands to remove excess salt' },
      { letter: 'D', text: 'a person with high blood pressure maintaining normal pressure levels through diet and exercise' },
    ],
    answer: 'C',
  },
  {
    n: 28,
    prompt: 'Which statement is true of meiosis?',
    choices: [
      { letter: 'A', text: 'Organisms use meiosis to grow.' },
      { letter: 'B', text: 'Organisms use meiosis to replace blood cells.' },
      { letter: 'C', text: 'Organisms use meiosis to repair damaged cells.' },
      { letter: 'D', text: 'Organisms use meiosis to make reproductive cells.' },
    ],
    answer: 'D',
  },
  {
    n: 29,
    prompt: 'Black fur (B) is dominant to white fur (b) in guinea pigs. An F1 cross was conducted and resulted in 100% heterozygous guinea pigs (Bb). What is the genotypic ratio outcome of the F2 generation?',
    choices: [
      { letter: 'A', text: '4 Bb' },
      { letter: 'B', text: '3 Bb : 1 bb' },
      { letter: 'C', text: '1 BB : 2 Bb : 1 bb' },
      { letter: 'D', text: '2 BB : 1 Bb : 1 bb' },
    ],
    answer: 'C',
  },
  {
    n: 30,
    prompt: 'In guinea pigs, rough coats (R) are dominant to smooth coats (r). A homozygous rough-coat guinea pig has offspring with a homozygous smooth-coat guinea pig. What percent of the offspring are predicted to have rough coats?',
    choices: [
      { letter: 'A', text: '0%' },
      { letter: 'B', text: '25%' },
      { letter: 'C', text: '50%' },
      { letter: 'D', text: '100%' },
    ],
    answer: 'D',
  },
  {
    n: 31,
    prompt: 'Color blindness is inherited as a sex-linked recessive disease. An affected male marries a female who is heterozygous for the trait. What percentage of their offspring will exhibit color blindness?',
    choices: [
      { letter: 'A', text: '0%' },
      { letter: 'B', text: '25%' },
      { letter: 'C', text: '50%' },
      { letter: 'D', text: '100%' },
    ],
    answer: 'C',
  },
  {
    n: 32,
    prompt: 'A father without hemophilia has two daughters and two sons. Neither daughter has hemophilia. One son has hemophilia and the other does not. What is the genotype of the mother?',
    choices: [
      { letter: 'A', text: 'XHXH' },
      { letter: 'B', text: 'XHXh' },
      { letter: 'C', text: 'XHY' },
      { letter: 'D', text: 'XhY' },
    ],
    answer: 'B',
  },
  {
    n: 33,
    prompt: 'The diagram below shows a process that frequently occurs during meiosis. What advantage is provided by this process?',
    choices: [
      { letter: 'A', text: 'Daughter cells maintain the same number of chromosomes as the parent cell.' },
      { letter: 'B', text: 'Daughter cells have half the number of chromosomes as the parent cell.' },
      { letter: 'C', text: 'Daughter cells are genetically different from parent cells.' },
      { letter: 'D', text: 'Daughter cells are genetically identical to parent cells.' },
    ],
    answer: 'C',
  },
  {
    n: 34,
    prompt: 'Crossing over between chromosomes occurs during which phase of meiosis?',
    choices: [
      { letter: 'A', text: 'interphase' },
      { letter: 'B', text: 'prophase I' },
      { letter: 'C', text: 'prophase II' },
      { letter: 'D', text: 'metaphase II' },
    ],
    answer: 'B',
  },
  {
    n: 35,
    prompt: 'Having freckles is dominant over not having freckles. If two individuals heterozygous for freckles have a child, what is the probability the child will have freckles?',
    choices: [
      { letter: 'A', text: '0%' },
      { letter: 'B', text: '25%' },
      { letter: 'C', text: '50%' },
      { letter: 'D', text: '75%' },
    ],
    answer: 'D',
  },
  {
    n: 36,
    prompt: 'Genetically identical plants will produce either pink flowers or blue flowers, depending on the type of soil in which they are planted. What is most likely the explanation for the differences in flower color?',
    choices: [
      { letter: 'A', text: 'The flower-color gene is codominant.' },
      { letter: 'B', text: 'Mutations alter the flower-color gene.' },
      { letter: 'C', text: 'The flower-color gene is sex-linked.' },
      { letter: 'D', text: 'Environmental factors affect flower color.' },
    ],
    answer: 'D',
  },
  {
    n: 37,
    prompt: 'How are mitosis and meiosis similar?',
    choices: [
      { letter: 'A', text: 'both have two cell divisions' },
      { letter: 'B', text: 'both require DNA replication' },
      { letter: 'C', text: 'both produce gametes' },
      { letter: 'D', text: 'both involve crossing over' },
    ],
    answer: 'B',
  },
  {
    n: 38,
    prompt: 'How do some chemicals increase the risk of a person getting cancer?',
    choices: [
      { letter: 'A', text: 'by causing cell mutations' },
      { letter: 'B', text: 'by causing a deficiency of vitamin D' },
      { letter: 'C', text: 'by causing an increase of toxins in the skin' },
      { letter: 'D', text: 'by causing a decrease in the immune response' },
    ],
    answer: 'A',
  },
  {
    n: 39,
    prompt: 'Which process can occur in both mitosis and meiosis?',
    choices: [
      { letter: 'A', text: 'fertilization' },
      { letter: 'B', text: 'independent assortment' },
      { letter: 'C', text: 'gene mutation' },
      { letter: 'D', text: 'crossing over' },
    ],
    answer: 'C',
  },
  {
    n: 40,
    prompt: 'Identical twin girls are separated at birth and cared for by two different families. After twenty years, the twins have different heights and weights. What is most likely the cause of these differences?',
    choices: [
      { letter: 'A', text: 'One twin had a genetic condition that prevented her from growing tall.' },
      { letter: 'B', text: 'The DNA of one twin was different from the DNA of the other twin.' },
      { letter: 'C', text: 'Each twin was provided a different diet and physical activities.' },
      { letter: 'D', text: 'The proteins made by one twin were different than the proteins made by the other twin.' },
    ],
    answer: 'C',
  },
  {
    n: 41,
    prompt: 'This is an mRNA codon chart. This table shows the sequence of a gene found in four separate organisms. Organism 1 AAC ACA TTA Organism 2 GAG ACA TTA Organism 3 AAC ACG TTT Organism 4 GAT ACG TTG Which organism would have a protein whose function differed from that found in the other organisms?',
    choices: [
      { letter: 'A', text: 'Organism 1' },
      { letter: 'B', text: 'Organism 2' },
      { letter: 'C', text: 'Organism 3' },
      { letter: 'D', text: 'Organism 4' },
    ],
    answer: 'C',
  },
  {
    n: 42,
    prompt: 'What is the main benefit to using genetically modified organisms, even though their use has sparked an ethical debate around the world?',
    choices: [
      { letter: 'A', text: 'Humans can produce more insulin naturally.' },
      { letter: 'B', text: 'Fewer pharmaceutical products are produced.' },
      { letter: 'C', text: 'Farm products have a more pleasing appearance.' },
      { letter: 'D', text: 'Fewer pesticides are released into the environment.' },
    ],
    answer: 'D',
  },
  {
    n: 43,
    prompt: 'Which best explains the genetic similarities between species?',
    choices: [
      { letter: 'A', text: 'More closely related species will have identical DNA.' },
      { letter: 'B', text: 'More closely related species will have fewer DNA similarities.' },
      { letter: 'C', text: 'More closely related species will have more similarities in DNA.' },
      { letter: 'D', text: 'There is no link between the relationships of species and their DNA.' },
    ],
    answer: 'C',
  },
  {
    n: 44,
    prompt: 'What is the main goal of the Human Genome Project?',
    choices: [
      { letter: 'A', text: 'to find cures for genetic diseases' },
      { letter: 'B', text: 'to find all mutations in human DNA' },
      { letter: 'C', text: 'to sequence all DNA on human chromosomes' },
      { letter: 'D', text: 'to count the number of genes in human DNA' },
    ],
    answer: 'C',
  },
  {
    n: 45,
    prompt: 'What is the goal of genetic engineering?',
    choices: [
      { letter: 'A', text: 'to create a stronger, more resilient organism' },
      { letter: 'B', text: 'to create a homozygous hybrid' },
      { letter: 'C', text: 'to map the organism’s genes' },
      { letter: 'D', text: 'to map a new set of genes' },
    ],
    answer: 'A',
  },
  {
    n: 46,
    prompt: 'A biochemist is working to isolate the insulin that a transgenic bacterial culture has produced. Which step of the transgenic process would have come right before the protein isolation?',
    choices: [
      { letter: 'A', text: 'Insulin is purified and packaged for use.' },
      { letter: 'B', text: 'Bacteria cells are induced to take in the insulin plasmid.' },
      { letter: 'C', text: 'Cultured bacterial cells are induced to make the transgenic protein.' },
      { letter: 'D', text: 'Restriction enzymes cut the plasmid for insertion of the insulin gene.' },
    ],
    answer: 'C',
  },
  {
    n: 47,
    prompt: 'Opponents of the genetic engineering of plants argue that it is difficult to accurately predict the consequences of plant alterations to the local habitat. Which is the most likely negative outcome of genetic modification in plants?',
    choices: [
      { letter: 'A', text: 'Genetically engineered plants would outcompete the local, native plants, causing massive die outs.' },
      { letter: 'B', text: 'Genetically engineered plants that are pest-resistant would reduce the local population of pollinating insects.' },
      { letter: 'C', text: 'Genetically engineered plants that are greener in appearance would be chosen more often as food by consumers.' },
      { letter: 'D', text: 'Genetically engineered plants would transfer genes to the local, native plants, creating new species that cannot be killed.' },
    ],
    answer: 'D',
  },
  {
    n: 48,
    prompt: 'The diagram below shows the steps in bacterial transformation. In which step would restriction enzymes most likely be used?',
    choices: [
      { letter: 'A', text: 'Step 1' },
      { letter: 'B', text: 'Step 2' },
      { letter: 'C', text: 'Step 3' },
      { letter: 'D', text: 'Step 4' },
    ],
    answer: 'A',
  },
  {
    n: 49,
    prompt: 'The diagram of the bacterial cell below shows the structures necessary for the creation of a transgenic organism. Which statement correctly identifies the structure labeled as Structure II and describes its role in creating a transgenic organism?',
    choices: [
      { letter: 'A', text: 'Structure II is a ribosome. The ribosome combines with the host organism’s genetic material to create recombinant DNA, which is then inserted into a host organism to create a transgenic organism.' },
      { letter: 'B', text: 'Structure II is a nucleus. The nucleus releases its genetic material to combine with the host organism’s mitochondria and create recombinant DNA, which is then inserted into a host organism to create a transgenic organism.' },
      { letter: 'C', text: 'Structure II is a bacterial plasmid. Genetic material is inserted into the plasmid, which is then placed into the cells of another organism where it combines with that organism’s chromosomes to create a transgenic organism.' },
      { letter: 'D', text: 'Structure II is a mitochondrion. Genetic material is inserted into the mitochondrion, which is then placed into the cells of another organism where it combines with that organism’s chromosomes to create a transgenic organism.' },
    ],
    answer: 'C',
  },
  {
    n: 50,
    prompt: 'The diagram below compares the DNA of a newly discovered bird (Bird 1) with four known bird species. Which bird is least likely related to Bird 1?',
    choices: [
      { letter: 'A', text: 'Bird 2' },
      { letter: 'B', text: 'Bird 3' },
      { letter: 'C', text: 'Bird 4' },
      { letter: 'D', text: 'Bird 5' },
    ],
    answer: 'D',
  },
  {
    n: 51,
    prompt: 'Why is stem cell research important within the field of medicine?',
    choices: [
      { letter: 'A', text: 'Stem cells have the potential to differentiate into many other types of cells.' },
      { letter: 'B', text: 'Unlike other types of cells, stem cells only replicate a limited number of times.' },
      { letter: 'C', text: 'Stem cells are differentiated cells that can become undifferentiated and turned into another cell type.' },
      { letter: 'D', text: 'Unlike other types of cells, stem cells are resistant to the mutations that change DNA sequences and cause cancer.' },
    ],
    answer: 'A',
  },
  {
    n: 52,
    prompt: 'Which approach would be least helpful in determining genetic differences between species?',
    choices: [
      { letter: 'A', text: 'analysis of DNA' },
      { letter: 'B', text: 'observation of mating habits' },
      { letter: 'C', text: 'examination of proteins encoded by DNA' },
      { letter: 'D', text: 'identification of amino acids that make up proteins' },
    ],
    answer: 'B',
  },
  {
    n: 53,
    prompt: 'What is one way transgenic organisms are used?',
    choices: [
      { letter: 'A', text: 'as a tool for breeding' },
      { letter: 'B', text: 'in cataloging endangered species' },
      { letter: 'C', text: 'in the production of human insulin' },
      { letter: 'D', text: 'in the identification of invasive species' },
    ],
    answer: 'C',
  },
  {
    n: 54,
    prompt: 'Which areas in society are most directly benefiting from the use of transgenic organisms?',
    choices: [
      { letter: 'A', text: 'politics and economics' },
      { letter: 'B', text: 'education and sports' },
      { letter: 'C', text: 'medicine and agriculture' },
      { letter: 'D', text: 'aerospace and architecture' },
    ],
    answer: 'C',
  },
  {
    n: 55,
    prompt: 'The diagram below shows the steps taken to genetically modify a bacterial cell with DNA from an animal donor. Which step represents creation of recombinant DNA?',
    choices: [
      { letter: 'A', text: 'Step 1' },
      { letter: 'B', text: 'Step 2' },
      { letter: 'C', text: 'Step 3' },
      { letter: 'D', text: 'Step 4' },
    ],
    answer: 'C',
  },
  {
    n: 56,
    prompt: 'The U.S. Food and Drug Administration has approved the use of cloned animals as food. Which statement describes the main health concern related to their use?',
    choices: [
      { letter: 'A', text: 'Cloning techniques sometimes lead to malformations in animals, which may cause food to be unsafe.' },
      { letter: 'B', text: 'Cloned animal products will be of lower quality than that of traditional animal products.' },
      { letter: 'C', text: 'Cloned cattle will dominate the market, putting traditional ranchers out of business.' },
      { letter: 'D', text: 'Cloned animals may carry new diseases that go undetected.' },
    ],
    answer: 'A',
  },
  {
    n: 57,
    prompt: 'Which would be a desirable trait scientists may want to create in a transgenic plant?',
    choices: [
      { letter: 'A', text: 'the ability to resist insects' },
      { letter: 'B', text: 'the ability to grow less fruit' },
      { letter: 'C', text: 'the ability to change color in the winter' },
      { letter: 'D', text: 'the ability to use a lot of water' },
    ],
    answer: 'A',
  },
  {
    n: 58,
    prompt: 'What is the function of a restriction enzyme?',
    choices: [
      { letter: 'A', text: 'to control the movement of proteins into a cell' },
      { letter: 'B', text: 'to regulate blood sugar levels' },
      { letter: 'C', text: 'to produce hormones that regulate digestion' },
      { letter: 'D', text: 'to cut DNA at a specific nucleotide sequence' },
    ],
    answer: 'D',
  },
  {
    n: 59,
    prompt: 'What is the difference between the DNA of a dog and the DNA of a fly?',
    choices: [
      { letter: 'A', text: 'the type of sugar building blocks' },
      { letter: 'B', text: 'the sequence of nucleotides' },
      { letter: 'C', text: 'the strength of hydrogen bonds' },
      { letter: 'D', text: 'the strength of covalent bonds' },
    ],
    answer: 'B',
  },
  {
    n: 60,
    prompt: 'Which transgenic organism has been used to clean up oil spills?',
    choices: [
      { letter: 'A', text: 'bacteria' },
      { letter: 'B', text: 'fungus' },
      { letter: 'C', text: 'jellyfish' },
      { letter: 'D', text: 'paramecia' },
    ],
    answer: 'A',
  },
  {
    n: 61,
    prompt: 'A population of beetles is mostly composed of individuals with the dominant green color, but there are several with the recessive brown color. A displaced species of bird moves into the habitat and preferentially preys upon the green beetles. Over time, what can be expected to happen to the beetle population?',
    choices: [
      { letter: 'A', text: 'The beetle population will become extinct.' },
      { letter: 'B', text: 'The brown beetles will become more common.' },
      { letter: 'C', text: 'The beetles will migrate to avoid being eaten by the birds in the habitat.' },
      { letter: 'D', text: 'The beetle population will stabilize because the birds will not eat more beetles than necessary to maintain ecological balance.' },
    ],
    answer: 'B',
  },
  {
    n: 62,
    prompt: 'Through which type of reproduction does natural selection work most effectively over time to influence differences in size, coloration, and ability to fight diseases within a species?',
    choices: [
      { letter: 'A', text: 'asexual reproduction' },
      { letter: 'B', text: 'sexual reproduction' },
      { letter: 'C', text: 'bud cell production' },
      { letter: 'D', text: 'spore production' },
    ],
    answer: 'B',
  },
  {
    n: 63,
    prompt: 'How does a population experience variation in traits?',
    choices: [
      { letter: 'A', text: 'through an increased birth rate' },
      { letter: 'B', text: 'through a decreased death rate' },
      { letter: 'C', text: 'through mutations and genetic recombination' },
      { letter: 'D', text: 'through the introduction of an invasive species' },
    ],
    answer: 'C',
  },
  {
    n: 64,
    prompt: 'Which situation would most likely be a driving force for changes in a species?',
    choices: [
      { letter: 'A', text: 'reduced diversity due to geographic isolation' },
      { letter: 'B', text: 'increased mating events due to environmental stability' },
      { letter: 'C', text: 'increased resources due to favorable weather conditions' },
      { letter: 'D', text: 'reduced offspring production due to asexual reproduction methods' },
    ],
    answer: 'A',
  },
  {
    n: 65,
    prompt: 'A certain strain of bacteria used to be susceptible to penicillin. Today, that strain is resistant to penicillin. Which best explains this observation?',
    choices: [
      { letter: 'A', text: 'The bacteria needed to become resistant to survive.' },
      { letter: 'B', text: 'The isolation of the strain caused it to become resistant.' },
      { letter: 'C', text: 'A mutation occurred and was passed to future generations.' },
      { letter: 'D', text: 'The mutation rate in the bacteria population greatly increased.' },
    ],
    answer: 'C',
  },
  {
    n: 66,
    prompt: 'How is inheritance related to the process of natural selection?',
    choices: [
      { letter: 'A', text: 'It promotes mutations of genetic material over time.' },
      { letter: 'B', text: 'It restricts the flow of DNA from one generation to the next.' },
      { letter: 'C', text: 'It reduces competition for mates and increases genetic continuity.' },
      { letter: 'D', text: 'It allows beneficial traits to be passed from generation to generation.' },
    ],
    answer: 'D',
  },
  {
    n: 67,
    prompt: 'Which choice best demonstrates how natural selection can occur within a population?',
    choices: [
      { letter: 'A', text: 'Competition within the population decreases because of unlimited resources.' },
      { letter: 'B', text: 'The organisms in the population experience genetic stability with regard to physical traits.' },
      { letter: 'C', text: 'The number of organisms in the population decreases because of a limited number of births.' },
      { letter: 'D', text: 'Females choose mates based on the brightness of the coloration of males within the population.' },
    ],
    answer: 'D',
  },
  {
    n: 68,
    prompt: 'The wing color of a population of moths darkens over time. Which statement best explains why the wing color changes?',
    choices: [
      { letter: 'A', text: 'An excess of smoke in the atmosphere caused the wings to darken.' },
      { letter: 'B', text: 'A decreased amount of water in the area caused the wings to darken.' },
      { letter: 'C', text: 'The frequencies of alleles for light wings was increased in the moth population.' },
      { letter: 'D', text: 'The frequencies of alleles for dark wings was increased in the moth population.' },
    ],
    answer: 'D',
  },
  {
    n: 69,
    prompt: 'Which mechanism has the least effect on natural selection over time?',
    choices: [
      { letter: 'A', text: 'mutation' },
      { letter: 'B', text: 'inheritance' },
      { letter: 'C', text: 'asexual reproduction' },
      { letter: 'D', text: 'environmental change' },
    ],
    answer: 'C',
  },
  {
    n: 70,
    prompt: 'The diagram below shows the effects of exposing bacteria to antibiotics. How does the diagram illustrate the occurrence of natural selection?',
    choices: [
      { letter: 'A', text: 'The final population looks exactly like the population after the antibiotics.' },
      { letter: 'B', text: 'The original bacteria were all killed by the antibiotics; thus, a new population was made.' },
      { letter: 'C', text: 'The antibiotics had no effect on the bacteria. The new population is the result of a spontaneous change.' },
      { letter: 'D', text: 'The antibiotics killed the bacteria that had a low resistance level. The new population formed from highly resistant bacteria.' },
    ],
    answer: 'D',
  },
  {
    n: 71,
    prompt: 'A patient has a severe bacterial infection. Within a few weeks of treatment with an antibiotic, the bacterial population consists entirely of antibiotic-resistant bacteria. How can this outcome most likely be explained?',
    choices: [
      { letter: 'A', text: 'The antibiotic caused a mutation in the bacteria’s RNA.' },
      { letter: 'B', text: 'The bacteria began reproducing at a faster rate than before the antibiotic treatment.' },
      { letter: 'C', text: 'The antibiotic created resistance in the bacteria, and the bacteria are passing the resistance to one another.' },
      { letter: 'D', text: 'A small population of antibiotic-resistant bacteria were present before the treatment, and natural selection increased their frequency.' },
    ],
    answer: 'D',
  },
  {
    n: 72,
    prompt: 'Which statement best defines natural selection?',
    choices: [
      { letter: 'A', text: 'Individuals with variation tend to live longer.' },
      { letter: 'B', text: 'Larger individuals tend to produce more offspring.' },
      { letter: 'C', text: 'Individuals better adapted to the environment tend to leave more offspring.' },
      { letter: 'D', text: 'Individuals put into a warm environment will have an increased rate of mutation.' },
    ],
    answer: 'C',
  },
  {
    n: 73,
    prompt: 'Environmental pressures cause changes in a population over time. Which mechanism most likely explains this outcome?',
    choices: [
      { letter: 'A', text: 'natural selection' },
      { letter: 'B', text: 'random mutation' },
      { letter: 'C', text: 'genetic engineering' },
      { letter: 'D', text: 'asexual reproduction' },
    ],
    answer: 'A',
  },
  {
    n: 74,
    prompt: 'A population of rabbits in an arctic environment includes some rabbits with dark-colored fur and some rabbits with light-colored fur. Which scenario best illustrates natural selection within the population?',
    choices: [
      { letter: 'A', text: 'The wolves in the arctic environment are able to prey upon rabbits with dark-colored fur more easily. Over time, the majority of the rabbits in the population are found to have light-colored fur.' },
      { letter: 'B', text: 'The wolves in the arctic environment compete with the rabbits with light-colored fur. Over time, the majority of the rabbits in the population are found to have dark-colored fur.' },
      { letter: 'C', text: 'The wolves in the arctic environment are restricted to a small habitat area, reducing the wolf population and allowing the rabbits with dark-colored fur to overpopulate the rest of the environment.' },
      { letter: 'D', text: 'The wolves in the arctic environment are overhunted by humans, reducing the wolf population and allowing the rabbits with light-colored fur to overpopulate the environment.' },
    ],
    answer: 'A',
  },
  {
    n: 75,
    prompt: 'Why does natural selection occur less frequently on organisms in a stable habitat?',
    choices: [
      { letter: 'A', text: 'There is less competition because resources are unlimited.' },
      { letter: 'B', text: 'Organisms already have the adaptations necessary for survival in a stable habitat.' },
      { letter: 'C', text: 'Populations are always surviving below their carrying capacity in a stable habitat.' },
      { letter: 'D', text: 'With little habitat change, all members of a population have equal reproductive capabilities.' },
    ],
    answer: 'B',
  },
  {
    n: 76,
    prompt: 'How would an organism most likely survive, reproduce, and pass on its alleles?',
    choices: [
      { letter: 'A', text: 'by having a brief life span' },
      { letter: 'B', text: 'by leaving its young alone' },
      { letter: 'C', text: 'by inheriting favorable adaptations' },
      { letter: 'D', text: 'by developing advantageous behaviors' },
    ],
    answer: 'C',
  },
  {
    n: 77,
    prompt: 'The table below shows population changes of the rock pocket mice, which live in the sandy Sonoran Desert of the United States. Time Percentage of Light-Colored Mice Percentage of Dark-Colored Mice before the volcanic eruption 89% 11% five years after the volcanic eruption 12% 88% ten years after the volcanic eruption 9% 91% Which statement explains the smaller percentage of dark-colored mice living in sandy substrate prior to the volcanic eruption?',
    choices: [
      { letter: 'A', text: 'It was easier for the light-colored mice to find food.' },
      { letter: 'B', text: 'It was easier for the dark-colored mice to find food.' },
      { letter: 'C', text: 'The allele for dark color became lethal in the mouse population.' },
      { letter: 'D', text: 'Predators had an easier time locating the dark-colored mice.' },
    ],
    answer: 'D',
  },
  {
    n: 78,
    prompt: 'When is natural selection most likely to occur?',
    choices: [
      { letter: 'A', text: 'when an ecosystem is going through an environmental change' },
      { letter: 'B', text: 'when gene flow is high among the populations in an ecosystem' },
      { letter: 'C', text: 'when there are enough resources in the ecosystem for the population to use' },
      { letter: 'D', text: 'when there are few genetic differences among individuals within a population' },
    ],
    answer: 'A',
  },
  {
    n: 79,
    prompt: 'Which adaptations would a population of mammals that live in extremely cold climates most likely develop over time through natural selection?',
    choices: [
      { letter: 'A', text: 'thick fur and a layer of fat' },
      { letter: 'B', text: 'long legs and a long neck' },
      { letter: 'C', text: 'webbed feet and feathers' },
      { letter: 'D', text: 'dark fur and large eyes' },
    ],
    answer: 'A',
  },
  {
    n: 80,
    prompt: 'The table below shows amino acid sequences in four different organisms. Organism Amino Acid Sequence 1 Met - Tyr - Arg - Ala - Pro - Glu 2 Met - Tyr - Arg - Ala - Tyr - Pro 3 Met - Tyr - Cys - Ala - Glu - Pro 4 Met - Tyr - Arg - Ala - Glu - Glu If these sequences code for proteins within the same protein family, which two organisms are most likely closely related to one another?',
    choices: [
      { letter: 'A', text: '1 and 2' },
      { letter: 'B', text: '1 and 4' },
      { letter: 'C', text: '2 and 3' },
      { letter: 'D', text: '2 and 4' },
    ],
    answer: 'B',
  },
  {
    n: 81,
    prompt: 'Which nucleic acid is correctly paired with its function?',
    choices: [
      { letter: 'A', text: 'mRNA: lines up amino acids at the ribosome' },
      { letter: 'B', text: 'DNA: forms peptide bonds between amino acids' },
      { letter: 'C', text: 'tRNA: moves genetic information from the nucleus to the ribosome' },
      { letter: 'D', text: 'mRNA: moves genetic information from the nucleus to the ribosome' },
    ],
    answer: 'D',
  },
  {
    n: 82,
    prompt: 'Which contains codons?',
    choices: [
      { letter: 'A', text: 'ribosomes' },
      { letter: 'B', text: 'mRNA' },
      { letter: 'C', text: 'rRNA' },
      { letter: 'D', text: 'tRNA' },
    ],
    answer: 'B',
  },
  {
    n: 83,
    prompt: 'Which process is a main component of protein synthesis?',
    choices: [
      { letter: 'A', text: 'replication' },
      { letter: 'B', text: 'reproduction' },
      { letter: 'C', text: 'transformation' },
      { letter: 'D', text: 'translation' },
    ],
    answer: 'D',
  },
  {
    n: 84,
    prompt: 'Which is not a step in protein synthesis?',
    choices: [
      { letter: 'A', text: 'tRNA brings in amino acids' },
      { letter: 'B', text: 'mRNA travels to the ribosome' },
      { letter: 'C', text: 'DNA polymerase reads the mRNA' },
      { letter: 'D', text: 'RNA polymerase makes mRNA from DNA' },
    ],
    answer: 'C',
  },
  {
    n: 85,
    prompt: 'In which area of the cell does the interaction between codon and anticodon occur?',
    choices: [
      { letter: 'A', text: 'Golgi body' },
      { letter: 'B', text: 'lysosome' },
      { letter: 'C', text: 'ribosome' },
      { letter: 'D', text: 'nucleus' },
    ],
    answer: 'C',
  },
  {
    n: 86,
    prompt: 'Which are units that make up proteins?',
    choices: [
      { letter: 'A', text: 'fatty acids' },
      { letter: 'B', text: 'amino acids' },
      { letter: 'C', text: 'glucose molecules' },
      { letter: 'D', text: 'nucleotide molecules' },
    ],
    answer: 'B',
  },
  {
    n: 87,
    prompt: 'Which role do proteins play in the body?',
    choices: [
      { letter: 'A', text: 'They provide long-term energy storage.' },
      { letter: 'B', text: 'They provide short-term energy storage.' },
      { letter: 'C', text: 'They provide structure to form DNA and RNA molecules.' },
      { letter: 'D', text: 'They provide structure for body tissue, hair, and fingernails.' },
    ],
    answer: 'D',
  },
  {
    n: 88,
    prompt: 'Which sequence determines the specific amino acids that link together to form proteins?',
    choices: [
      { letter: 'A', text: 'the sequence of nuclei in RNA' },
      { letter: 'B', text: 'the sequence of ribosomes in RNA' },
      { letter: 'C', text: 'the sequence of nucleotides in DNA' },
      { letter: 'D', text: 'the sequence of amino acids in DNA' },
    ],
    answer: 'C',
  },
  {
    n: 89,
    prompt: 'The diagram below shows a polypeptide sequence and a codon chart. Which DNA sequence most likely provided the instructions for the addition of the second amino acid, serine (SER), in the polypeptide sequence?',
    choices: [
      { letter: 'A', text: 'AGT' },
      { letter: 'B', text: 'CAC' },
      { letter: 'C', text: 'GCC' },
      { letter: 'D', text: 'GTG' },
    ],
    answer: 'A',
  },
  {
    n: 90,
    prompt: 'Which best explains how genetic information is used to cause cellular processes?',
    choices: [
      { letter: 'A', text: 'The order of nucleotides in DNA governs which proteins will be translated.' },
      { letter: 'B', text: 'The order of nucleotides in DNA governs which proteins will be transcribed.' },
      { letter: 'C', text: 'The order of nucleotides in DNA governs which proteins will be replicated.' },
      { letter: 'D', text: 'The order of nucleotides in DNA governs which proteins will be destroyed.' },
    ],
    answer: 'A',
  },
  {
    n: 91,
    prompt: 'Which best summarizes the role of DNA in the production of proteins?',
    choices: [
      { letter: 'A', text: 'DNA moves to the cytoplasm to build proteins.' },
      { letter: 'B', text: 'DNA transports amino acids to the ribosomes to make proteins.' },
      { letter: 'C', text: 'DNA contains the instructions used to make proteins.' },
      { letter: 'D', text: 'DNA breaks hydrogen bonds between amino acids.' },
    ],
    answer: 'C',
  },
  {
    n: 92,
    prompt: 'Waxes create a waterproof layer on the outside of some living organisms. To which group of organic molecules do waxes belong?',
    choices: [
      { letter: 'A', text: 'carbohydrates' },
      { letter: 'B', text: 'lipids' },
      { letter: 'C', text: 'nucleic acids' },
      { letter: 'D', text: 'proteins' },
    ],
    answer: 'B',
  },
  {
    n: 93,
    prompt: 'Salivary amylase is an enzyme in humans that breaks down starches. What substance would humans have difficulty digesting without this enzyme?',
    choices: [
      { letter: 'A', text: 'lipids' },
      { letter: 'B', text: 'nucleic acids' },
      { letter: 'C', text: 'proteins' },
      { letter: 'D', text: 'carbohydrates' },
    ],
    answer: 'D',
  },
  {
    n: 94,
    prompt: 'Which molecules are joined together to make proteins?',
    choices: [
      { letter: 'A', text: 'fatty acids' },
      { letter: 'B', text: 'nucleic acids' },
      { letter: 'C', text: 'amino acids' },
      { letter: 'D', text: 'acetic acids' },
    ],
    answer: 'C',
  },
  {
    n: 95,
    prompt: 'Which best explains why the rate of a biochemical reaction decreases at high temperatures?',
    choices: [
      { letter: 'A', text: 'The activation energy increases.' },
      { letter: 'B', text: 'The shape of the enzyme changes.' },
      { letter: 'C', text: 'The enzyme-substrate complex forms.' },
      { letter: 'D', text: 'The bonds between substrates are broken.' },
    ],
    answer: 'B',
  },
  {
    n: 96,
    prompt: 'A peptide bond forms when a covalent bond links two amino acids together. Which structural formula represents a peptide bond?',
    choices: [
      { letter: 'A', text: '' },
      { letter: 'B', text: '' },
      { letter: 'C', text: '' },
      { letter: 'D', text: '' },
    ],
    answer: 'C',
  },
  {
    n: 97,
    prompt: 'Which biomolecule does NOT have a carbon-nitrogen bond?',
    choices: [
      { letter: 'A', text: 'protein' },
      { letter: 'B', text: 'peptide' },
      { letter: 'C', text: 'nucleic acid' },
      { letter: 'D', text: 'carbohydrate' },
    ],
    answer: 'D',
  },
  {
    n: 98,
    prompt: 'The diagram shows the basic structure of a biomolecule. Based on the structure, which material will dissolve this biomolecule the BEST?',
    choices: [
      { letter: 'A', text: 'oil' },
      { letter: 'B', text: 'dilute alcohol' },
      { letter: 'C', text: 'water' },
      { letter: 'D', text: 'ionic solution' },
    ],
    answer: 'A',
  },
  {
    n: 99,
    prompt: 'How are the functions of a carbohydrate and a lipid similar?',
    choices: [
      { letter: 'A', text: 'Both are a source of energy.' },
      { letter: 'B', text: 'Both are replicated during meiosis.' },
      { letter: 'C', text: 'Both lower the activation energy of reactions.' },
      { letter: 'D', text: 'Both dissolve nutrients in the digestive system.' },
    ],
    answer: 'A',
  },
  {
    n: 100,
    prompt: 'Biomolecules contain a variety of atoms. Which biomolecule maintains a ratio of 1 carbon atom to 2 hydrogen atoms to 1 oxygen atom?',
    choices: [
      { letter: 'A', text: 'lipid' },
      { letter: 'B', text: 'protein' },
      { letter: 'C', text: 'nucleic acid' },
      { letter: 'D', text: 'carbohydrate' },
    ],
    answer: 'D',
  },
  {
    n: 101,
    prompt: 'This diagram shows three different ways molecules can move from one side of a cell membrane to the other. Which movement(s) of molecules across the cell membrane is active transport?',
    choices: [
      { letter: 'A', text: 'Y only' },
      { letter: 'B', text: 'Z only' },
      { letter: 'C', text: 'X and Y' },
      { letter: 'D', text: 'X and Z' },
    ],
    answer: 'B',
  },
  {
    n: 102,
    prompt: 'The products from cellular respiration are used in which other chemical process?',
    choices: [
      { letter: 'A', text: 'Krebs cycle' },
      { letter: 'B', text: 'fermentation' },
      { letter: 'C', text: 'photosynthesis' },
      { letter: 'D', text: 'anaerobic respiration' },
    ],
    answer: 'C',
  },
  {
    n: 103,
    prompt: 'Which type of transport is most likely to be used to move a product made inside a cell to the extracellular matrix?',
    choices: [
      { letter: 'A', text: 'diffusion' },
      { letter: 'B', text: 'active transport' },
      { letter: 'C', text: 'passive transport' },
      { letter: 'D', text: 'facilitated diffusion' },
    ],
    answer: 'B',
  },
  {
    n: 104,
    prompt: 'Which statement correctly compares aerobic and anaerobic respiration?',
    choices: [
      { letter: 'A', text: 'Anaerobic respiration occurs in the presence of oxygen but aerobic respiration does not.' },
      { letter: 'B', text: 'Fermentation occurs during aerobic respiration but not during anaerobic respiration.' },
      { letter: 'C', text: 'Aerobic respiration produces 36 ATP, while anaerobic respiration produces only 2 ATP.' },
      { letter: 'D', text: 'Aerobic respiration produces 2 ATP, while anaerobic respiration produces 36 ATP.' },
    ],
    answer: 'C',
  },
  {
    n: 105,
    prompt: 'How does the cell membrane use the ATP produced by the cell’s mitochondria?',
    choices: [
      { letter: 'A', text: 'to replace damaged phospholipids' },
      { letter: 'B', text: 'to produce receptors for hormones' },
      { letter: 'C', text: 'to move water into or out of the cell' },
      { letter: 'D', text: 'to transport ions against their concentration gradient' },
    ],
    answer: 'D',
  },
  {
    n: 106,
    prompt: 'How is energy stored at the end of aerobic respiration?',
    choices: [
      { letter: 'A', text: 'as ADP' },
      { letter: 'B', text: 'as ATP' },
      { letter: 'C', text: 'as NAPH' },
      { letter: 'D', text: 'as FADH2' },
    ],
    answer: 'B',
  },
  {
    n: 107,
    prompt: 'The experiment below shows pond weed as it undergoes photosynthesis. Which reactant is not labeled in the diagram?',
    choices: [
      { letter: 'A', text: 'carbon monoxide' },
      { letter: 'B', text: 'carbon dioxide' },
      { letter: 'C', text: 'nitrogen gas' },
      { letter: 'D', text: 'phosphorus' },
    ],
    answer: 'B',
  },
  {
    n: 108,
    prompt: 'Which statement best describes the processes of photosynthesis and cellular respiration?',
    choices: [
      { letter: 'A', text: 'Photosynthesis is an energy-storing process because it produces glucose, and respiration is an energy-releasing process because it produces ATP.' },
      { letter: 'B', text: 'Photosynthesis is an energy-releasing process because it produces glucose, and respiration is an energy-storing process because it produces ATP.' },
      { letter: 'C', text: 'Photosynthesis is an energy-storing process because it produces ATP and oxygen, and respiration is an energy-releasing process because it produces carbon dioxide and water.' },
      { letter: 'D', text: 'Photosynthesis is an energy-releasing process because it produces ATP and oxygen, and respiration is an energy-storing process because it produces carbon dioxide and water.' },
    ],
    answer: 'A',
  },
  {
    n: 109,
    prompt: 'Which word equation best represents the process of cellular respiration?',
    choices: [
      { letter: 'A', text: 'carbon dioxide + glucose → oxygen + water' },
      { letter: 'B', text: 'carbon dioxide + water → glucose + oxygen' },
      { letter: 'C', text: 'glucose + oxygen → carbon dioxide + water' },
      { letter: 'D', text: 'oxygen + water → carbon dioxide + glucose' },
    ],
    answer: 'C',
  },
  {
    n: 110,
    prompt: 'A contractile vacuole helps protists eliminate excess liquid. This is a “pumping" process which reduces pressure inside the cell and prevents the cell from bursting. What is most likely the source of energy for this process?',
    choices: [
      { letter: 'A', text: 'DNA' },
      { letter: 'B', text: 'lipids' },
      { letter: 'C', text: 'ATP' },
      { letter: 'D', text: 'ribosomes' },
    ],
    answer: 'C',
  },
  {
    n: 111,
    prompt: 'How does the body of a runner keep up with the demand for energy when cellular oxygen levels are low?',
    choices: [
      { letter: 'A', text: 'through energy production in the mitochondria' },
      { letter: 'B', text: 'through aerobic respiration in the plasma membrane' },
      { letter: 'C', text: 'through ATP produced directly from sunlight' },
      { letter: 'D', text: 'through anaerobic respiration in the cytoplasm' },
    ],
    answer: 'D',
  },
  {
    n: 112,
    prompt: 'A student noticed that the freshwater plant, Elodea, produced bubbles when placed in direct light. What could the student most likely conclude?',
    choices: [
      { letter: 'A', text: 'Bubbles of carbon dioxide were produced as a result of photosynthesis.' },
      { letter: 'B', text: 'Bubbles of oxygen were produced as a result of photosynthesis.' },
      { letter: 'C', text: 'Bubbles of carbon dioxide were produced as a result of cellular respiration.' },
      { letter: 'D', text: 'Bubbles of oxygen were produced as a result of cellular respiration.' },
    ],
    answer: 'B',
  },
  {
    n: 113,
    prompt: 'During photosynthesis, plants convert sunlight into what substance to be used for energy?',
    choices: [
      { letter: 'A', text: 'oxygen' },
      { letter: 'B', text: 'carbon dioxide' },
      { letter: 'C', text: 'iron sulfide' },
      { letter: 'D', text: 'glucose' },
    ],
    answer: 'D',
  },
  {
    n: 114,
    prompt: 'When animals use energy, what is always produced?',
    choices: [
      { letter: 'A', text: 'sugar' },
      { letter: 'B', text: 'heat' },
      { letter: 'C', text: 'oxygen' },
      { letter: 'D', text: 'starch' },
    ],
    answer: 'B',
  },
  {
    n: 115,
    prompt: 'What does the following word equation represent?',
    choices: [
      { letter: 'A', text: 'photosynthesis' },
      { letter: 'B', text: 'regeneration' },
      { letter: 'C', text: 'respiration' },
      { letter: 'D', text: 'transpiration' },
    ],
    answer: 'C',
  },
  {
    n: 116,
    prompt: 'Which of the following represents the process of photosynthesis?',
    choices: [
      { letter: 'A', text: '' },
      { letter: 'B', text: '' },
      { letter: 'C', text: '' },
      { letter: 'D', text: '' },
    ],
    answer: 'A',
  },
  {
    n: 117,
    prompt: 'Which of the following is produced during the process of cellular respiration?',
    choices: [
      { letter: 'A', text: 'carbon dioxide' },
      { letter: 'B', text: 'sodium chloride' },
      { letter: 'C', text: 'oxygen' },
      { letter: 'D', text: 'sugar' },
    ],
    answer: 'A',
  },
  {
    n: 118,
    prompt: 'The concentration of sodium and potassium ions inside and outside a nerve cell must be reset each time the transmission of a nerve impulse occurs. Both ion types are able to move across the nerve cell membrane against the concentration gradient. To maintain these gradients, nerve cells depend directly on the chemical output of which other cell process?',
    choices: [
      { letter: 'A', text: 'mitosis' },
      { letter: 'B', text: 'replication' },
      { letter: 'C', text: 'respiration' },
      { letter: 'D', text: 'transcription' },
    ],
    answer: 'C',
  },
  {
    n: 120,
    prompt: 'Glucose molecules provide the chemical energy cells use to carry on life processes. Some energy is always lost when cells break down the glucose molecules. Which statement explains how energy is lost in this process?',
    choices: [
      { letter: 'A', text: 'Some energy is changed back to glucose.' },
      { letter: 'B', text: 'Some energy is converted into mass.' },
      { letter: 'C', text: 'Some energy is converted into heat.' },
      { letter: 'D', text: 'Some energy is changed into ADP.' },
    ],
    answer: 'C',
  },
  {
    n: 121,
    prompt: 'These images show two different cells. How are these cells classified?',
    choices: [
      { letter: 'A', text: 'Cell 1 is a eukaryotic cell, while Cell 2 is a prokaryotic cell.' },
      { letter: 'B', text: 'Cell 1 is a prokaryotic cell, while Cell 2 is a eukaryotic cell.' },
      { letter: 'C', text: 'Cell 1 and Cell 2 are both eukaryotic cells.' },
      { letter: 'D', text: 'Cell 1 and Cell 2 are both prokaryotic cells.' },
    ],
    answer: 'A',
  },
  {
    n: 122,
    prompt: 'What determines cell differentiation once gene regulation has taken place?',
    choices: [
      { letter: 'A', text: 'fluids' },
      { letter: 'B', text: 'proteins' },
      { letter: 'C', text: 'mitochondria' },
      { letter: 'D', text: 'adenosine triphosphates' },
    ],
    answer: 'B',
  },
  {
    n: 123,
    prompt: 'How are the enzymes that nerve cells produce different from the enzymes that blood cells produce?',
    choices: [
      { letter: 'A', text: 'Nerve cells contain more ribosomes than blood cells.' },
      { letter: 'B', text: 'Nerve cells contain more mitochondria than blood cells.' },
      { letter: 'C', text: 'The genes that are activated in nerve cells are different from those activated in blood cells.' },
      { letter: 'D', text: 'The molecules that nerve cells digest are more complex than those digested by blood cells.' },
    ],
    answer: 'C',
  },
  {
    n: 124,
    prompt: 'A student uses a microscope to observe a cell that has a cell wall, a plasma membrane, and circular DNA. What kind of cell is this student observing?',
    choices: [
      { letter: 'A', text: 'plant cell' },
      { letter: 'B', text: 'animal cell' },
      { letter: 'C', text: 'eukaryotic cell' },
      { letter: 'D', text: 'prokaryotic cell' },
    ],
    answer: 'D',
  },
  {
    n: 125,
    prompt: 'A unicellular organism has a cell wall, a nucleus, chloroplasts, and several flagella. Which classification best matches this organism?',
    choices: [
      { letter: 'A', text: 'eukaryotic plant' },
      { letter: 'B', text: 'eukaryotic protist' },
      { letter: 'C', text: 'prokaryotic eubacteria' },
      { letter: 'D', text: 'prokaryotic archaebacteria' },
    ],
    answer: 'B',
  },
  {
    n: 126,
    prompt: 'How do stem cells become specialized to absorb nutrients from food as intestinal cells?',
    choices: [
      { letter: 'A', text: 'by gene removal' },
      { letter: 'B', text: 'by gene activation' },
      { letter: 'C', text: 'through translation' },
      { letter: 'D', text: 'through transcription' },
    ],
    answer: 'B',
  },
  {
    n: 127,
    prompt: 'A scientist discovers several new prokaryotic organisms near a deep seafloor vent. Which best describes the general characteristics of these organisms?',
    choices: [
      { letter: 'A', text: 'colonial, autotrophic' },
      { letter: 'B', text: 'multicellular, autotrophic' },
      { letter: 'C', text: 'single-celled, autotrophic' },
      { letter: 'D', text: 'multicellular, heterotrophic' },
    ],
    answer: 'C',
  },
  {
    n: 128,
    prompt: 'Which is most likely true of prokaryotic cells?',
    choices: [
      { letter: 'A', text: 'They are large, complex cells.' },
      { letter: 'B', text: 'Their DNA is contained in the nucleus.' },
      { letter: 'C', text: 'Their organelles are surrounded by membranes.' },
      { letter: 'D', text: 'They evolved on Earth before eukaryotic cells.' },
    ],
    answer: 'D',
  },
  {
    n: 129,
    prompt: 'In which organelle is DNA found in a eukaryotic cell?',
    choices: [
      { letter: 'A', text: 'nucleus' },
      { letter: 'B', text: 'vacuole' },
      { letter: 'C', text: 'Golgi apparatus' },
      { letter: 'D', text: 'smooth endoplasmic reticulum' },
    ],
    answer: 'A',
  },
  {
    n: 130,
    prompt: 'Which statement best describes the difference between prokaryotes and eukaryotes with regard to DNA?',
    choices: [
      { letter: 'A', text: 'Prokaryotic DNA is helical, while eukaryotic DNA is circular.' },
      { letter: 'B', text: 'Prokaryotic DNA is circular, while eukaryotic DNA is helical.' },
      { letter: 'C', text: 'Prokaryotic DNA is single stranded, while eukaryotic DNA is triple stranded.' },
      { letter: 'D', text: 'Prokaryotic DNA is membrane bound, while eukaryotic DNA is located in the cell wall.' },
    ],
    answer: 'B',
  },
  {
    n: 131,
    prompt: 'Which statement is true?',
    choices: [
      { letter: 'A', text: 'Prokaryotic cells have a nucleus.' },
      { letter: 'B', text: 'Eukaryotic cells have organelles.' },
      { letter: 'C', text: 'Eukaryotic cells have no organelles.' },
      { letter: 'D', text: 'Prokaryotic cells have no organelles.' },
    ],
    answer: 'B',
  },
  {
    n: 132,
    prompt: 'Which most accurately describes the location of DNA in prokaryotic cells and in eukaryotic cells?',
    choices: [
      { letter: 'A', text: 'Eukaryotic cells have DNA only in the cytoplasm, and prokaryotic cells have DNA in the cell membrane.' },
      { letter: 'B', text: 'Eukaryotic cells have DNA in the cell membrane, and prokaryotic cells have DNA in the cytoplasm.' },
      { letter: 'C', text: 'Eukaryotic cells have DNA only in the cytoplasm, and prokaryotic cells have DNA in the nucleus.' },
      { letter: 'D', text: 'Eukaryotic cells have DNA in the nucleus, and prokaryotic cells have DNA in the cytoplasm.' },
    ],
    answer: 'D',
  },
  {
    n: 133,
    prompt: 'Which is not a characteristic of prokaryotes?',
    choices: [
      { letter: 'A', text: 'circular DNA' },
      { letter: 'B', text: 'cell specialization' },
      { letter: 'C', text: 'presence of ribosomes' },
      { letter: 'D', text: 'lack of membrane-bound organelles' },
    ],
    answer: 'B',
  },
  {
    n: 134,
    prompt: 'A student examines a sample of cells under a microscope. The student observes the cells to have a box-like shape with ribosomes, mitochondria, membrane-bound nuclei, and large central vacuoles. What type of cell sample is the student most likely observing?',
    choices: [
      { letter: 'A', text: 'animal' },
      { letter: 'B', text: 'bacteria' },
      { letter: 'C', text: 'plant' },
      { letter: 'D', text: 'virus' },
    ],
    answer: 'C',
  },
  {
    n: 135,
    prompt: 'Which type of cell is considered the least complex?',
    choices: [
      { letter: 'A', text: 'animal' },
      { letter: 'B', text: 'eukaryote' },
      { letter: 'C', text: 'plant' },
      { letter: 'D', text: 'prokaryote' },
    ],
    answer: 'D',
  },
  {
    n: 136,
    prompt: 'How do eukaryotic and prokaryotic cells differ?',
    choices: [
      { letter: 'A', text: 'Only prokaryotic cells contain ribosomes.' },
      { letter: 'B', text: 'Only eukaryotic cells come from pre-existing cells.' },
      { letter: 'C', text: 'Only prokaryotic cells come from pre-existing cells.' },
      { letter: 'D', text: 'Only eukaryotic cells contain membrane-bound organelles.' },
    ],
    answer: 'D',
  },
  {
    n: 137,
    prompt: 'John is viewing a cell under a high-powered microscope. Which would indicate that the cell John is looking at is a eukaryote?',
    choices: [
      { letter: 'A', text: 'the presence of DNA' },
      { letter: 'B', text: 'the presence of ribosomes' },
      { letter: 'C', text: 'the presence of mitochondria' },
      { letter: 'D', text: 'the presence of a cell membrane' },
    ],
    answer: 'C',
  },
  {
    n: 138,
    prompt: 'What structures do prokaryotic and eukaryotic cells have in common?',
    choices: [
      { letter: 'A', text: 'ribosomes, mitochondria, and DNA' },
      { letter: 'B', text: 'vacuoles, nucleus, and mitochondria' },
      { letter: 'C', text: 'cell membrane, ribosomes, and DNA' },
      { letter: 'D', text: 'cell membrane, mitochondria, and DNA' },
    ],
    answer: 'C',
  },
  {
    n: 139,
    prompt: 'Which statement about the genes of specialized cells is true?',
    choices: [
      { letter: 'A', text: 'Each specialized cell in an organism contains a different set of genes.' },
      { letter: 'B', text: 'All the specialized cells of an organism contain the exact same genes.' },
      { letter: 'C', text: 'The specialized cells of an organism contain half as many genes as its unspecialized cells.' },
      { letter: 'D', text: 'The specialized cells of an organism contain twice as many genes as its unspecialized cells.' },
    ],
    answer: 'B',
  },
  {
    n: 140,
    prompt: 'Which explains how Euglena move toward light?',
    choices: [
      { letter: 'A', text: 'They use cilia for reproduction.' },
      { letter: 'B', text: 'They use cilia for photosynthesis.' },
      { letter: 'C', text: 'They use a flagellum for positive phototaxis.' },
      { letter: 'D', text: 'They use a contractile vacuole for negative phototaxis.' },
    ],
    answer: 'C',
  },
  {
    n: 141,
    prompt: 'A cell is placed in a hypertonic solution. Which will most likely occur as homeostasis is maintained in the cell?',
    choices: [
      { letter: 'A', text: 'The cell will lose water.' },
      { letter: 'B', text: 'The cell will gain water.' },
      { letter: 'C', text: 'The cell will lose sodium ions.' },
      { letter: 'D', text: 'The cell will gain ATP molecules.' },
    ],
    answer: 'A',
  },
  {
    n: 142,
    prompt: 'What does a Euglena require to exhibit phototactic behavior?',
    choices: [
      { letter: 'A', text: 'cilia' },
      { letter: 'B', text: 'an eyespot' },
      { letter: 'C', text: 'a pseudopod' },
      { letter: 'D', text: 'a contractile vacuole' },
    ],
    answer: 'B',
  },
  {
    n: 143,
    prompt: 'A saltwater plant is placed in fresh water. What will most likely happen to the cells of the plant?',
    choices: [
      { letter: 'A', text: 'The cell wall will prevent water from flowing in or out of the cells.' },
      { letter: 'B', text: 'The cells will lose water and shrivel.' },
      { letter: 'C', text: 'The cells will gain water and swell.' },
      { letter: 'D', text: 'The cells will stay the same size.' },
    ],
    answer: 'C',
  },
  {
    n: 144,
    prompt: 'How would the presence of cilia, flagella, and pseudopods improve the chances of survival of a unicellular protist?',
    choices: [
      { letter: 'A', text: 'by decreasing the rate of cell division' },
      { letter: 'B', text: 'by increasing the rate of water exchange' },
      { letter: 'C', text: 'by decreasing the energy needs of the organism' },
      { letter: 'D', text: 'by increasing the likelihood of obtaining nutrients' },
    ],
    answer: 'D',
  },
  {
    n: 145,
    prompt: 'How does it benefit a euglena to have both chloroplasts and a gullet?',
    choices: [
      { letter: 'A', text: 'by increasing its camouflage' },
      { letter: 'B', text: 'by providing motility and nutrition' },
      { letter: 'C', text: 'by allowing it to be both heterotrophic and autotrophic' },
      { letter: 'D', text: 'by helping multiple organelles maintain their shape in different environments' },
    ],
    answer: 'C',
  },
  {
    n: 146,
    prompt: 'How do Euglena and sperm cells use flagella?',
    choices: [
      { letter: 'A', text: 'for locomotion' },
      { letter: 'B', text: 'for detecting light' },
      { letter: 'C', text: 'for waste removal' },
      { letter: 'D', text: 'for maintaining homeostasis' },
    ],
    answer: 'A',
  },
  {
    n: 147,
    prompt: 'How does a Euglena identify a light source and move toward it so photosynthesis can occur?',
    choices: [
      { letter: 'A', text: 'by using eyespots and flagella' },
      { letter: 'B', text: 'by using pseudopodia and flagella' },
      { letter: 'C', text: 'by using contractile vacuoles and cilia' },
      { letter: 'D', text: 'by using contractile vacuoles and pseudopodia' },
    ],
    answer: 'A',
  },
  {
    n: 148,
    prompt: 'How does a flagellum aid a single-celled organism?',
    choices: [
      { letter: 'A', text: 'by capturing food' },
      { letter: 'B', text: 'by causing movement' },
      { letter: 'C', text: 'by providing camouflage' },
      { letter: 'D', text: 'by improving reproduction' },
    ],
    answer: 'B',
  },
  {
    n: 149,
    prompt: 'What role does an eyespot play in a single-celled organism?',
    choices: [
      { letter: 'A', text: 'It senses the location of air.' },
      { letter: 'B', text: 'It senses the location of light.' },
      { letter: 'C', text: 'It senses the location of oxygen.' },
      { letter: 'D', text: 'It senses the location of toxic chemicals.' },
    ],
    answer: 'B',
  },
  {
    n: 150,
    prompt: 'Which purpose does a cell membrane play in eukaryotic cells?',
    choices: [
      { letter: 'A', text: 'It digests waste.' },
      { letter: 'B', text: 'It maintains homeostasis.' },
      { letter: 'C', text: 'It translates cellular proteins.' },
      { letter: 'D', text: 'It creates energy to fuel cell processes.' },
    ],
    answer: 'B',
  },
  {
    n: 151,
    prompt: 'Pepsin, an enzyme that is found in the stomach of humans, functions in breaking down proteins. It is denatured as it travels to the small intestine and can no longer decompose proteins. Which factor most likely causes the enzyme to denature as it moves through the digestive tract?',
    choices: [
      { letter: 'A', text: 'pH' },
      { letter: 'B', text: 'temperature' },
      { letter: 'C', text: 'enzyme concentration' },
      { letter: 'D', text: 'substrate concentration' },
    ],
    answer: 'A',
  },
  {
    n: 152,
    prompt: 'The human body utilizes water to balance body temperature. Under what conditions might thermal regulation break down and no longer function correctly?',
    choices: [
      { letter: 'A', text: 'decreased physical activity' },
      { letter: 'B', text: 'increased digestive activity' },
      { letter: 'C', text: 'high water intake and low water output' },
      { letter: 'D', text: 'low water intake and high water output' },
    ],
    answer: 'D',
  },
  {
    n: 153,
    prompt: 'What would happen to a freshwater protozoan if it were placed in a tank of salt water?',
    choices: [
      { letter: 'A', text: 'It would lose water through osmosis.' },
      { letter: 'B', text: 'It would gain water through osmosis.' },
      { letter: 'C', text: 'It would lose water through active transport.' },
      { letter: 'D', text: 'It would gain water through active transport.' },
    ],
    answer: 'A',
  },
  {
    n: 154,
    prompt: 'A protist is placed in a container of distilled water. How would the protist most likely survive these conditions?',
    choices: [
      { letter: 'A', text: 'by using flagella' },
      { letter: 'B', text: 'by using eyespots' },
      { letter: 'C', text: 'by using pseudopodia' },
      { letter: 'D', text: 'by using contractile vacuoles' },
    ],
    answer: 'D',
  },
  {
    n: 155,
    prompt: 'What adaptation allows an organism to pump excess water out of a cell?',
    choices: [
      { letter: 'A', text: 'cilia' },
      { letter: 'B', text: 'flagella' },
      { letter: 'C', text: 'eyespot' },
      { letter: 'D', text: 'contractile vacuole' },
    ],
    answer: 'D',
  },
  {
    n: 156,
    prompt: 'How do single-celled organisms move and gather food by phagocytosis?',
    choices: [
      { letter: 'A', text: 'by replicating' },
      { letter: 'B', text: 'by photosynthesizing' },
      { letter: 'C', text: 'by using pseudopodia' },
      { letter: 'D', text: 'by using contractile vacuoles' },
    ],
    answer: 'C',
  },
  {
    n: 157,
    prompt: 'How do contractile vacuoles help organisms survive?',
    choices: [
      { letter: 'A', text: 'They aid in movement.' },
      { letter: 'B', text: 'They prevent ultraviolet damage.' },
      { letter: 'C', text: 'They collect and expel excess water.' },
      { letter: 'D', text: 'They provide organisms with nourishment.' },
    ],
    answer: 'C',
  },
  {
    n: 158,
    prompt: 'Which cell specialization helps a Euglena increase its rate of photosynthesis?',
    choices: [
      { letter: 'A', text: 'cilia' },
      { letter: 'B', text: 'an eyespot' },
      { letter: 'C', text: 'pseudopodia' },
      { letter: 'D', text: 'a contractile vacuole' },
    ],
    answer: 'B',
  },
  {
    n: 159,
    prompt: 'Which cell adaptation is required for a single-celled organism to exhibit phototaxis?',
    choices: [
      { letter: 'A', text: 'cilia' },
      { letter: 'B', text: 'flagella' },
      { letter: 'C', text: 'eyespot' },
      { letter: 'D', text: 'pseudopod' },
    ],
    answer: 'C',
  },
];
