/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneysIndexRouteImport } from './routes/journeys/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as PlaySessionIdRouteImport } from './routes/play.$sessionId'
import { Route as JourneysIdRouteImport } from './routes/journeys/$id'
import { Route as ContentStatsRouteImport } from './routes/content/stats'
import { Route as ContentModulesRouteImport } from './routes/content/modules'
import { Route as ContentImportRouteImport } from './routes/content/import'
import { Route as ContentFormatRouteImport } from './routes/content/format'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySessionIdRoute = PlaySessionIdRouteImport.update({
  id: '/play/$sessionId',
  path: '/play/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIdRoute = JourneysIdRouteImport.update({
  id: '/journeys/$id',
  path: '/journeys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentStatsRoute = ContentStatsRouteImport.update({
  id: '/content/stats',
  path: '/content/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentModulesRoute = ContentModulesRouteImport.update({
  id: '/content/modules',
  path: '/content/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentImportRoute = ContentImportRouteImport.update({
  id: '/content/import',
  path: '/content/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentFormatRoute = ContentFormatRouteImport.update({
  id: '/content/format',
  path: '/content/format',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/garden': typeof GardenRoute
  '/notebook': typeof NotebookRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/content/format': typeof ContentFormatRoute
  '/content/import': typeof ContentImportRoute
  '/content/modules': typeof ContentModulesRoute
  '/content/stats': typeof ContentStatsRoute
  '/journeys/$id': typeof JourneysIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/content/': typeof ContentIndexRoute
  '/journeys/': typeof JourneysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/garden': typeof GardenRoute
  '/notebook': typeof NotebookRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/content/format': typeof ContentFormatRoute
  '/content/import': typeof ContentImportRoute
  '/content/modules': typeof ContentModulesRoute
  '/content/stats': typeof ContentStatsRoute
  '/journeys/$id': typeof JourneysIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/content': typeof ContentIndexRoute
  '/journeys': typeof JourneysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/garden': typeof GardenRoute
  '/notebook': typeof NotebookRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/content/format': typeof ContentFormatRoute
  '/content/import': typeof ContentImportRoute
  '/content/modules': typeof ContentModulesRoute
  '/content/stats': typeof ContentStatsRoute
  '/journeys/$id': typeof JourneysIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/content/': typeof ContentIndexRoute
  '/journeys/': typeof JourneysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/garden'
    | '/notebook'
    | '/settings'
    | '/welcome'
    | '/content/format'
    | '/content/import'
    | '/content/modules'
    | '/content/stats'
    | '/journeys/$id'
    | '/play/$sessionId'
    | '/content/'
    | '/journeys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/garden'
    | '/notebook'
    | '/settings'
    | '/welcome'
    | '/content/format'
    | '/content/import'
    | '/content/modules'
    | '/content/stats'
    | '/journeys/$id'
    | '/play/$sessionId'
    | '/content'
    | '/journeys'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/garden'
    | '/notebook'
    | '/settings'
    | '/welcome'
    | '/content/format'
    | '/content/import'
    | '/content/modules'
    | '/content/stats'
    | '/journeys/$id'
    | '/play/$sessionId'
    | '/content/'
    | '/journeys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GardenRoute: typeof GardenRoute
  NotebookRoute: typeof NotebookRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  ContentFormatRoute: typeof ContentFormatRoute
  ContentImportRoute: typeof ContentImportRoute
  ContentModulesRoute: typeof ContentModulesRoute
  ContentStatsRoute: typeof ContentStatsRoute
  JourneysIdRoute: typeof JourneysIdRoute
  PlaySessionIdRoute: typeof PlaySessionIdRoute
  ContentIndexRoute: typeof ContentIndexRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$sessionId': {
      id: '/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/play/$sessionId'
      preLoaderRoute: typeof PlaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$id': {
      id: '/journeys/$id'
      path: '/journeys/$id'
      fullPath: '/journeys/$id'
      preLoaderRoute: typeof JourneysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/stats': {
      id: '/content/stats'
      path: '/content/stats'
      fullPath: '/content/stats'
      preLoaderRoute: typeof ContentStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/modules': {
      id: '/content/modules'
      path: '/content/modules'
      fullPath: '/content/modules'
      preLoaderRoute: typeof ContentModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/import': {
      id: '/content/import'
      path: '/content/import'
      fullPath: '/content/import'
      preLoaderRoute: typeof ContentImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/format': {
      id: '/content/format'
      path: '/content/format'
      fullPath: '/content/format'
      preLoaderRoute: typeof ContentFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GardenRoute: GardenRoute,
  NotebookRoute: NotebookRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  ContentFormatRoute: ContentFormatRoute,
  ContentImportRoute: ContentImportRoute,
  ContentModulesRoute: ContentModulesRoute,
  ContentStatsRoute: ContentStatsRoute,
  JourneysIdRoute: JourneysIdRoute,
  PlaySessionIdRoute: PlaySessionIdRoute,
  ContentIndexRoute: ContentIndexRoute,
  JourneysIndexRoute: JourneysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
